#https://docs.travis-ci.com/user/customizing-the-build/
#compilers in Travis: https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
#also: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
#Coverity: https://scan.coverity.com/travis_ci
# script: 

language: cpp
sudo: false
dist: xenial

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILER=g++-7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - libc++-7-dev
            - libc++abi-7-dev

      env:
        - COMPILER=clang++

script:
  - ./ci-builds/build.sh
